version: "3" 
services: 
  db: 
    image: mysql:8.0.19 
    container_name: mysql_container
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:8080
    volumes:
      - .:/usr/src/app
    command: air